#pragma once
#include <vector>
#include <iostream>

#define FULL_SCREEN_WIDTH 1600
#define FULL_SCREEN_HEIGHT 800
#define SCREEN_WDITH 800
#define SCREEN_HEIGHT 800
#define GRID_DEMO

#ifdef GRID_DEMO
#define FIRST_WINDOW_LEFT_EDGE -1.0f
#define FIRST_WINDOW_RIGHT_EDGE 1.0f
#define SECOND_WINDOW_LEFT_EDGE 0.0f
#define SECOND_WINDOW_RIGHT_EDGE 1.0f
#define CELL_WIDTH (SCREEN_WDITH)/(MAP_WIDTH)
#define CELL_HEIGHT (SCREEN_HEIGHT)/(MAP_HEIGHT)
#define MAP_STEP_SIZE_WIDTH (1.0 / MAP_WIDTH) * 2
#define MAP_STEP_SIZE_HEIGHT (1.0 / MAP_HEIGHT) * 2

#else
#define CELL_WIDTH (SCREEN_WDITH)/((MAP_WIDTH))
#define CELL_HEIGHT (SCREEN_HEIGHT)/(MAP_HEIGHT)
#define MAP_STEP_SIZE_WIDTH (1.0 / MAP_WIDTH) * 2
#define MAP_STEP_SIZE_HEIGHT (1.0 / MAP_HEIGHT) * 2
#endif

#define MAP_WIDTH 10
#define MAP_HEIGHT 10
#define XPIXEL 2 / SCREEN_WDITH
#define YPIXEL 2 / SCREEN_HEIGHT

#define MOVEMENT_FACTOR 30
#define ROTATION_FACTOR 2

#define NORMAL_TO_PIXEL_X(normal) int((normal + 1) * (SCREEN_WDITH)/2)
#define NORMAL_TO_PIXEL_Y(normal) int((normal + 1) * (SCREEN_HEIGHT)/2)
#define PIXEL_TO_NORMAL(pixel) double(((pixel)*2))/(SCREEN_HEIGHT - 1)
